sudo: required
services:
  - docker
before_install:
  - docker build -t rupeshpanwar/multistagedockerapp -f Dockerfile.dev .
script:
  - docker run  -e CI=true rupeshpanwar/multistagedockerapp npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-075890588897"
  bucket_path: "docker"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true